# AutoGuía - Docker Compose para desarrollo local
version: '3.8'

services:
  # Solo servicios necesarios para desarrollo
  # Base de datos principal para AutoGuía
  autoguia-db:
    image: postgres:15-alpine
    container_name: autoguia-db-dev
    environment:
      POSTGRES_DB: autoguia_dev
      POSTGRES_USER: autoguia_dev
      POSTGRES_PASSWORD: dev123
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - autoguia-dev-network
    restart: unless-stopped

  # Base de datos separada para Identity
  identity-db:
    image: postgres:15-alpine
    container_name: identity-db-dev
    environment:
      POSTGRES_DB: identity_dev
      POSTGRES_USER: identity_dev
      POSTGRES_PASSWORD: dev123
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-identity-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - autoguia-dev-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: autoguia-redis-dev
    command: redis-server --appendonly yes
    volumes:
      - redis-dev-data:/data
    ports:
      - "6380:6379"
    networks:
      - autoguia-dev-network
    restart: unless-stopped

  # Adminer para desarrollo
  adminer:
    image: adminer:latest
    container_name: autoguia-adminer-dev
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: autoguia-db
    depends_on:
      - autoguia-db
      - identity-db
    networks:
      - autoguia-dev-network
    restart: unless-stopped

volumes:
  postgres-dev-data:
    driver: local
  postgres-identity-data:
    driver: local
  redis-dev-data:
    driver: local

networks:
  autoguia-dev-network:
    driver: bridge