name: Backups Cron

on:
  schedule:
    - cron: '0 2 * * *' # Runs every day at 2 AM UTC

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install PostgreSQL client tools
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Create backup directories
        run: |
          mkdir -p ~/backups
          mkdir -p ~/backups/logs

      - name: Execute database backup
        run: |
          TIMESTAMP=$(date +"%Y%m%d%H%M%S")
          BACKUP_FILE=~/backups/db_backup_$TIMESTAMP.sql
          PGPASSWORD=${{ secrets.PG_PASSWORD }} pg_dump -h ${{ secrets.PG_HOST }} -U ${{ secrets.PG_USER }} -F c -b -v -f $BACKUP_FILE ${DATABASE_NAME}

      - name: Compress backup
        run: gzip ~/backups/db_backup_$TIMESTAMP.sql

      - name: Move backup to logs
        run: mv ~/backups/db_backup_$TIMESTAMP.sql.gz ~/backups/logs/